{% set name = "mbstrdecoder" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcfd2c759322eb44fe193a9e0b1b86c5b87f3ec5ea8e1bb43b3e9ae423f1e8fe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - chardet >=3.0.4,<6
    - python >=3.5

test:
  imports:
    - mbstrdecoder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/mbstrdecoder
  summary: multi-byte character string decoder
  dev_url: https://github.com/thombashi/mbstrdecoder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
